services:
  mysql:
    image: mysql:8.0
    container_name: franchises-mysql
    environment:
      MYSQL_DATABASE: franchises_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
