server:
  port: 8080

spring:
  application:
    name: franchises-api

  datasource:
    url: jdbc:mysql://localhost:3307/franchises_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
